name: Savage-Frontier
version: '1.0'
main: com.darkbladedev.SavageFrontierMain
description: Aumenta la dificultad de tu survival con Savage Frontier.
api-version: '1.20.4'
bootstrapper: com.darkbladedev.CustomTypes.Bootstraps

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: true
      join-classpath: true

    AuraSkills:
      load: BEFORE
      required: true
      join-classpath: true
    