name: Winterfall
version: '1.0'
main: com.darkbladedev.WinterfallMain
description: Plugin que recrea el mundo de "El Eternauta" con mecánicas, items y mobs realistas.
api-version: '1.21.4'
bootstrapper: com.darkbladedev.CustomTypes.Bootstraps

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: true
      join-classpath: true

    SCore:
      load: BEFORE
      required: true
      join-classpath: true

    