name: Winterfall
version: 1.0.0
main: com.darkbladedev.WinterfallMain
api-version: 1.21
description: Plugin que recrea el mundo de "El Eternauta" con mecánicas, items y mobs realistas.
author: DarkBladeDev
depend: [PlaceholderAPI]
commands:
  winterfall:
    description: Comando principal del plugin Winterfall
    usage: /winterfall <subcomando>
    aliases: [wf]

permissions:
  winterfall.bypass.water:
    description: Permiso para bypasear el sistema de hidratación
    default: false
  winterfall.bypass.nutrients:
    description: Permiso para bypasear el sistema de nutrición
    default: false
  winterfall.bypass.stamina:
    description: Permiso para bypasear el sistema de estamina
    default: false